apiVersion: apps/v1
kind: Deployment
metadata:
  name: pets-ms
spec:
  replicas: 1
  selector:
    matchLabels:
      deployment: pets-ms
  template:
    metadata:
      labels:
        deployment: pets-ms
    spec:
      containers:
        - name: pets-ms
          image: gcr.io/PROJECT_ID/IMAGE:TAG
          ports:
            - containerPort: 9090
